name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 22.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
